# vapt_db.py
# VAPT Test Case Database for nmap_to_mindmap.py
# Each entry: port_number -> list of test cases
# Each test case is either:
#   str           -> leaf node in mindmap
#   (str, [list]) -> parent node with children

_REDIS_TC = [
    'nmap --script redis-info',
    'Nmap banner grabber (Version: 5.0.7)',
    'telnet connect',
    'redis-brute',
    'redis-info',
    'msf exploit/linux/redis/redis_unauth_exec',
    'Redis Command Execute Scanner',
    'Redis Login Utility',
    'Redis Lua Sandbox Escape',
    'Redis RCE',
    'Redis Extractor',
    'Sensitive information disclosure',
    ('Service Version Disclosure', ['Current: 5.0.7']),
    ('End of Life', [
        'Latest Version 7.0',
        'https://docs.redis.com/latest/rs/installing-upgrading/product-lifecycle/',
    ]),
]

_MYSQL_TC = [
    'Connect to server',
    'mysql-brute',
    'mysql-databases',
    'mysql-info',
    'MySQL Server Version Enumeration',
    ('mysql version end of life', ['Latest Version: 8.0.33', 'https://endoflife.date/mysql']),
    ('Outdated version', ['Current version: 5.5.30']),
    ('CVE', [
        'CVE-2012-2122',
        ('CVE-2011-5049', ['DOS']),
    ]),
    'nmap -script mysql-audit,mysql-databases,mysql-dump-hashes,mysql-empty-password,mysql-enum,mysql-info,mysql-query,mysql-users,mysql-variables',
]

_MSRPC_TC = [
    'use auxiliary/scanner/dcerpc/endpoint_mapper',
    'use auxiliary/scanner/dcerpc/hidden',
    'use auxiliary/scanner/dcerpc/management',
    'use auxiliary/scanner/dcerpc/tcp_dcerpc_auditor',
    'exploit/windows/dcerpc/ms03_026_dcom',
    'Unused port',
]

_NFS_TC = [
    'nfs-ls',
    'nfs-showmount',
    'nfs-statfd',
    'NFS Mount Scanner',
]

VAPT_DB = {
    21: [
        'Anonymous FTP Access Detection',
        'FTP Bounce Port Scanner',
        'FTP Version Scanner',
        'Sensible port open',
        'No CVE',
    ],
    22: [
        ('Try Common creds', ['using public key authentication']),
        'ssh-audit.py',
        'Check brute force',
        'nmap ssh* scripts',
        'nmap ssh2-enum-algos',
        ('Service Version Disclosure', ['SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5']),
        'SSH Weak Algorithms Supported',
        'Sensible Port is Publicly Accessible',
        'SSH Weak Key Exchange Algorithms Enabled',
        'SSH Weak MAC Algorithms Enabled',
        'SSH Server CBC Mode Ciphers Enabled',
        ('outdated version', ['Latest version: OpenSSH 9.3/9.3p1']),
        ('CVE', [
            ('CVE-2021-41617', ['Local Side']),
            ('CVE-2020-15778', ['permission denied - Target using public key authentication']),
            'CVE-2018-15919',
            'CVE-2016-20012',
        ]),
    ],
    25: [
        ('metasploit smtp_version', ['remote host: blrds-fw1', 'MTA agent: Postfix']),
        'metasploit smtp_enum',
        'smtp-open-relay',
        'smtp-enum-users',
        ('smtp-commands', [
            'blrdc-fw1, SIZE, VRFY, ETRN, ENHANCEDSTATUSCODES, 8BITMIME, DSN, CHUNKING',
            'vrfy command seems to be blocked',
        ]),
        'smtp-vuln-cve2010-4344',
        'smtp-vuln-cve2011-1720',
        'smtp-vuln-cve2011-1764',
        ('Open mail relay', [
            'mail from external email to ext email',
            'mail from external email to internal email',
            'mail from internal email to internal email',
        ]),
    ],
    80: [
        'Default installation page available',
        'run dirsearch/dirbuster',
        'run http-enum script',
        'MS15-034',
        'Run all http nmap scripts',
        'Try use auxiliary/scanner/http/dir_scanner & auxiliary/scanner/http/dir_listing',
        'use exploit/windows/iis/iis_webdav_upload_asp',
        'Only use https, kindly disable port 80',
        ('Microsoft UPnP Local Privilege Elevation Vulnerability', [
            'https://www.rapid7.com/db/modules/exploit/windows/local/comahawk/',
            'Requires authenticated user',
        ]),
        'http-sap-netweaver-leak.nse',
        ('CVE', [
            'CVE-2022-22532',
            'CVE-2022-22533',
            'CVE-2021-38163',
            'CVE-2020-6286',
            'CVE-2020-6287',
        ]),
        'Dirsearch',
        ('http-traceroute', ['Possible reverse proxy detected']),
        'http-enum',
        'http-dombased-xss',
        'http-slowloris',
        ('http-waf-detect', ['IDS/IPS/WAF detected']),
        'http-csrf',
        'http-xssed',
    ],
    81: [
        'Elasticsearch Unrestricted Access Information Disclosure',
        'dirsearch',
        'nmap http script',
        'check for default pgs',
        'http enum nmap',
        'check http supported methods',
        'http security headers',
        'http devframework - find technology used',
        'check authentication disabled',
        'basic user enum',
        ('check for indices pg', ['http://IP:81/_cat/indices?v']),
        ('check for dump index value', ['http://IP:81/auth/_search?pretty=true']),
        'check write permission',
        ('automatic enum', ['displays indices']),
        'outdated version',
        ('CVE-2021-22137', ['no exploit']),
        ('Perform the test cases mentioned in this link', [
            'https://www.youtube.com/watch?v=lUBw_RzXvEc',
            'performed TCs mentioned in video',
        ]),
        ('Dump All contents', ['dumps indices value - obtained info could not be used to further escalate the attack']),
        'Perform the attacks present in metasploit /scanner',
    ],
    111: [
        'rpcinfo',
        'Endpoint Mapper Service Discovery',
        'NFS Mount Scanner',
        'SunRPC Portmap Program Enumerator',
        ('RPC DoS targeting *nix rpcbind/libtirpc', ['DOS']),
        ('CVE', [
            ('CVE-2017-8779', ['DOS']),
            ('CVE-2015-7236', ['DOS']),
            ('CVE-2010-2064', ['Local']),
        ]),
    ],
    135: _MSRPC_TC,
    139: [
        'smb-Enum-shares domains, services, etc script',
        'rpcdump.py from Impacket to dump the RPC information',
        'Run all SMB nmap 35 script (Wildcard)',
        ('Run smb scanner metasploit and check results', [
            'https://www.offensive-security.com/metasploit-unleashed/scanner-smb-auxiliary-modules/',
        ]),
        'auxiliary/scanner/smb/smb_ms17_010 check for eternalblue if vulnerable',
        'use exploit/windows/smb/ms08_067_netapi',
        'Check SMB protocol v1 if used nmap->smb-protocols',
        'smb-security-mode --> check if signing required',
        'MS17-010 EternalRomance',
        'SMBGhost - CVE-2020-0796',
    ],
    264: [
        ('metasploit checkpoint_hostname', ['SmartCenter Host: BLR-DVSNL-MGMT']),
        'CVE: 2001-1303',
        'nmap scripts',
    ],
    443: [
        'SSL version 3 used',
        'SSL/TLS Diffie-Hellman Modulus <= 1024 Bits (Logjam)',
        'Vulnerable to SWEET32',
        'SSL CBC mode ciphers enabled',
        'SSL Supports RC4 Cipher Suites',
        'Run dirbuster and check sensitive endpoints',
        'Run wildcard nmap ssl scripts',
        'TLS v1.0 and 1.1 is used',
        'Check version and version related exploit',
    ],
    445: [
        'Enum-shares',
        'enum-users',
        'smb-vuln-ms17-010',
        'smb-os-discovery',
        'nbstat',
        'smb-enum-services',
        'Run all SMB nmap 35 script (Wildcard)',
        'Run smb scanner metasploit and check results',
        'auxiliary/scanner/smb/smb_ms17_010 check for eternalblue if vulnerable',
        'Try metasploit SMB_LOOKUPSID and check results',
        'Use SMB_VERSION and check',
        'use exploit/windows/smb/ms08_067_netapi',
        'Anonymous login: smbclient -L <host>',
    ],
    500: [
        'Try to connect using telnet & check service',
        'Try to fetch banner using nmap banner script',
        'Default installation page available',
        'Check version related issues',
        ('Try ike-scan and check', ['False - No hash coming']),
        'unused port',
    ],
    1128: [
        ('Service Version Disclosure', ['gSOAP 2.7']),
        ('Outdated Version', ['Latest Version: 2.8.107']),
        'SOAP Service RFC_SYSTEM_INFO Function Sensitive Information Gathering',
        'Dirsearch',
        'No CVE',
    ],
    1433: [
        ('ms-sql info', ['Microsoft SQL Server 15.00.4123.00']),
        'ms-sql-config',
        'ms-sql-brute',
        'ms-sql-ntlm-info',
        'Run nmap script as ms-sql*',
        'Metasploit (admin/mssql/mssql_enum_domain_accounts)',
        'Metasploit (admin/mssql/mssql_enum)',
        'Metasploit (admin/mssql/mssql_exec)',
        'Search Interesting data: auxiliary/admin/mssql/mssql_findandsampledata',
        'Try code execution: admin/mssql/mssql_exec & /mssql/mssql_payload',
        'Check sql version is out of date',
        'Try to connect using HeidiSQL',
    ],
    1527: [
        'Oracle-brute-stealth',
        'Service Version Disclosure',
        'oracle-brute',
        'oracle-enum-users',
        'oracle-sid-brute',
        'oracle-tns-version',
        'Oracle TNS Listener Checker',
        'oracle-tns-poison',
        'Oracle TNS Listener Command Issuer',
        'Oracle TNS Listener SID Brute Forcer',
        'Oracle TNS Listener SID Enumeration',
        'Oracle TNS Listener Service Version Query',
        ('CVE', ['CVE-2012-1675']),
    ],
    2049: _NFS_TC,
    2383: [
        'Try to connect using telnet',
        'Try to fetch banner using nmap banner script',
        'Run MSSQL exploit and check for results',
    ],
    3389: [
        'check multiple vulnerabilities using rdp-vuln-ms12-020 nmap script',
        'Run wildcard for rdp nmap scripts',
        'Check for metasploit cve_2019_0708_bluekeep_rce',
        'Try to access RDP with admin',
        'rdp-vuln-ms12-020',
        'Check if 3389 is publicly accessible',
        'Windows RDP',
    ],
    5257: [
        'Default installation page available',
        'run gobuster',
        'run http-enum script',
        'MS15-034',
        'Run all http nmap scripts',
        'Try use auxiliary/scanner/http/dir_scanner & auxiliary/scanner/http/dir_listing',
        'use exploit/windows/iis/iis_webdav_upload_asp',
        'Unused port',
    ],
    5984: [
        'Default installation page',
        'nmap -sV --script couchdb-databases,couchdb-stats',
        ('Priv Esc using CURL', [
            'curl -X GET http://IP:5984',
            'curl -X GET http://IP:5984/_all_dbs',
        ]),
        ('Try to fetch banner using nmap banner script', ['Apache CouchDB 3.1.0']),
        ('outdated version', ['Latest version: 3.3.2']),
        ('dirsearch', ['nothing found']),
        'CVE-2022-24706',
        'CVE-2021-38295',
    ],
    5985: [
        'Try to connect using telnet & check service',
        'Try to fetch banner using nmap banner script',
        'use auxiliary/scanner/winrm/winrm_auth_methods',
        'use auxiliary/scanner/winrm/winrm_login',
        'Default installation page available',
        'use auxiliary/scanner/upnp/ssdp_msearch',
        'Unused port',
        'Gobuster',
    ],
    6002: [
        'nmap -sV --script x11-access',
        'nmap banner grabber script',
        'xdpyinfo -display IP:0',
        'unnecessary port open',
        'nmap rdp script',
    ],
    6032: _MYSQL_TC,
    6033: _MYSQL_TC,
    6370: _REDIS_TC,
    6371: _REDIS_TC,
    6372: _REDIS_TC,
    6373: _REDIS_TC,
    6374: _REDIS_TC,
    6375: _REDIS_TC,
    6376: _REDIS_TC,
    6377: _REDIS_TC,
    6378: _REDIS_TC,
    6379: _REDIS_TC,
    6380: _REDIS_TC,
    6381: _REDIS_TC,
    6382: _REDIS_TC,
    7002: [
        'default page',
        ('Outdated version', [
            'Current version: 19.7.1',
            'Latest version: 20.1.0',
            'https://github.com/benoitc/gunicorn/releases',
        ]),
        'nmap http-vuln',
        'dirsearch',
        'unnecessary port open',
    ],
    7003: [
        'default page',
        ('Outdated version', [
            'Current version: 20.0.4',
            'Latest version: 20.1.0',
            'https://github.com/benoitc/gunicorn/releases',
        ]),
        'nmap http-vuln',
        'unnecessary port open',
    ],
    7004: [
        'default page',
        'dirsearch',
        'nmap --script=vuln',
        'unnecessary port open',
    ],
    7009: [
        'Username and Password brute force',
        'default page',
        'default password',
        ('outdated version', ['Current version: 6.1', 'Latest version: 6.3.2']),
        'check basic authentication',
    ],
    8001: [
        'script=vuln',
        'Django Debug error page',
        'Django admin brute force',
        ('dirsearch', ['nothing found']),
        'unnecessary port open',
    ],
    8002: [
        'script=vuln',
        'Django Debug error page',
        'Django admin brute force',
        ('Python version end of life', ['Latest version: 3.10', 'https://devguide.python.org/versions/']),
        ('Outdated version', ['Current version: 3.6.9']),
        'nmap related script',
    ],
    8004: [
        'Username and Password brute force',
        'default page',
        'default password',
        ('outdated version', ['Current version: 6.1', 'Latest version: 6.3.2']),
    ],
    8005: [
        'script=vuln',
        'Django Debug error page',
        ('Python version end of life', ['Latest version: 3.10', 'https://devguide.python.org/versions/']),
        ('Outdated version', ['Current version: 3.6.9']),
        'unnecessary port open',
    ],
    8009: [
        'default page',
        ('Outdated version', [
            'Current version: 20.0.4',
            'Latest version: 20.1.0',
            'https://github.com/benoitc/gunicorn/releases',
        ]),
        'nmap http-vuln',
        'unnecessary port open',
    ],
    8069: [
        'script=vuln',
        'Django Debug error page',
        ('Python version end of life', ['Latest version: 3.10', 'https://devguide.python.org/versions/']),
        ('Outdated version', ['Current version: 3.6.9']),
        'unnecessary port open',
    ],
    8072: [
        'default page',
        'dirsearch',
        'nmap --script=vuln',
        'unnecessary port open',
    ],
    8080: [
        'default page',
        ('Outdated version', [
            'Current version: 20.0.4',
            'Latest version: 20.1.0',
            'https://github.com/benoitc/gunicorn/releases',
        ]),
        'nmap http-vuln',
        'unnecessary port open',
    ],
    8081: [
        'dirsearch',
        ('JQuery version end of life', ['Latest version: 3.7.0', 'https://endoflife.date/jquery']),
        ('Outdated version', ['Current version: 1.10.2']),
    ],
    8083: [
        'dirsearch',
        ('JQuery version end of life', ['Latest version: 3.7.0', 'https://endoflife.date/jquery']),
        ('Outdated version', ['Current version: 1.10.2']),
    ],
    8091: [
        'default page',
        'dirsearch',
        'nmap --script=vuln',
        'nmap rtsp method',
    ],
    8093: [
        'default page',
        ('Outdated version', [
            'Current version: 20.0.4',
            'Latest version: 20.1.0',
            'https://github.com/benoitc/gunicorn/releases',
        ]),
        'nmap http-vuln',
    ],
    8095: [
        'default page',
        ('Outdated version', [
            'Current version: 19.7.1',
            'Latest version: 20.1.0',
            'https://github.com/benoitc/gunicorn/releases',
        ]),
        'nmap http-vuln',
        'unnecessary port open',
    ],
    8099: [
        'default page',
        ('Outdated version', [
            'Current version: 19.7.1',
            'Latest version: 20.1.0',
            'https://github.com/benoitc/gunicorn/releases',
        ]),
        'nmap http-vuln',
        'unnecessary port open',
    ],
    8181: [
        'default page',
        'dirsearch',
        'nmap --script=vuln',
        'unnecessary port open',
    ],
    8888: [
        'script=vuln',
        'Django Debug error page',
        ('Python version end of life', ['Latest version: 3.10', 'https://devguide.python.org/versions/']),
        ('Outdated version', ['Current version: 3.6.9']),
        'unnecessary port open',
    ],
    8922: [
        'default page',
        ('Outdated version', [
            'Current version: 20.0.4',
            'Latest version: 20.1.0',
            'https://github.com/benoitc/gunicorn/releases',
        ]),
        'nmap http-vuln',
        'unnecessary port open',
    ],
    8990: [
        'script=vuln',
        'Django Debug error page',
        ('Python version end of life', ['Latest version: 3.10', 'https://devguide.python.org/versions/']),
        ('Outdated version', ['Current version: 3.6.9']),
        ('Django end of life', [
            'Latest version: 4.2.3',
            'https://endoflife.date/django',
            'Current version: 2.1.3',
        ]),
        'enumerate port',
    ],
    9001: [
        'dirsearch',
        'default page',
        'nmap --script=vuln',
        'default credentials',
        'Minio default creds',
    ],
    9765: [
        'script=vuln',
        'Django Debug error page',
        ('Python version end of life', ['Latest version: 3.10', 'https://devguide.python.org/versions/']),
        ('Outdated version', ['Current version: 3.6.9']),
        'unnecessary port open',
    ],
    9998: [
        'script=vuln',
        'Django Debug error page',
        ('Python version end of life', ['Latest version: 3.10', 'https://devguide.python.org/versions/']),
        ('Outdated version', ['Current version: 3.6.9']),
        'unnecessary port open',
    ],
    18264: [
        'Unknown ports are running on the server',
    ],
    27017: [
        'nmap --script "mongo* and default"',
        ('nmap --script mongodb-brute', ['No authentication needed']),
        ('Version end of life', ['Latest version: 7.0', 'https://www.mongodb.com/support-policy/lifecycles']),
        'Database unauthenticated connection',
    ],
    27018: [
        'nmap --script "mongo* and default"',
        ('nmap --script mongodb-brute', ['No authentication needed']),
        ('Version end of life', ['Latest version: 7.0', 'https://www.mongodb.com/support-policy/lifecycles']),
        'Database unauthenticated connection',
    ],
    49667: _MSRPC_TC,
}

# UDP-specific test cases
VAPT_DB_UDP = {
    53: [
        'dns-brute nmap',
        'dig record A',
        'dig record AAAA',
        'dig record CNAME',
        'dig record MX',
        'zone transfer axfr',
        'DNS enum port 53 - nslookup, dig',
    ],
    68: [
        'netcat to connect to open udp port',
        'nmap dhcp discover',
        ('yersinia for port 68 -dhcp', ['requires src mac address and other info']),
    ],
    111: [
        'rpcinfo',
        'Endpoint Mapper Service Discovery',
        'NFS Mount Scanner',
        'SunRPC Portmap Program Enumerator',
        ('RPC DoS targeting *nix rpcbind/libtirpc', ['DOS']),
        ('CVE', [
            ('CVE-2017-8779', ['DOS']),
            ('CVE-2015-7236', ['DOS']),
            ('CVE-2010-2064', ['Local']),
        ]),
    ],
    123: [
        'nmap ntp-info',
        'ntp version disclose',
        'nmap ntp-*',
        ('ntpq command', ['try ntpq sysinfo', 'ntpq peers']),
    ],
    161: [
        ('snmp Nmap scripts', [('snmpinfo', ['true'])]),
        ('SNMP Community Login Scanner', ['False']),
        ('Service Version Disclosure', ['SNMPv3']),
        ('SNMP Enumeration Module', ['false']),
        ('SNMPv3 user enumerator', ['False']),
        ('SNMP Version 3 Authentication Bypass Vulnerabilities', ['false']),
    ],
    1194: [
        'check for openvpn version',
        'version related exploits',
        'netcat open port',
    ],
    2049: _NFS_TC + [
        'NFS Share User Mountable',
        'NFS Exported Share Information Disclosure',
    ],
}
